<?php
/**
 * @file
 * Simple messaging using html page. Messaging method plug-in
 * 
 * This is a really simple message viewer and also an illustration of pulling messaging methods
 */

// Number of messages to display per page
define('MESSAGING_DEBUG_PAGER', 10);

/**
 * Implementation of hook_menu().
 */
function messaging_debug_menu() {
  $items['user/%user/messagelog'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Message log',
    'page callback' => 'messaging_debug_user_page',
    'page arguments' => array(1),
    'access callback' => 'messaging_debug_access',
    'access arguments' => array(1),
  );
  return $items;
}

/**
 * Access calback
 */
function messaging_debug_access($account) {
  global $user;
  return $account->uid && (($account->uid == $user->uid) || user_access('administer messaging'));
}

/**
 * Implementation of hook_block()
 */
function messaging_debug_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Debug: Post message');
      $blocks[1]['info'] = t('Debug: Incoming message');
      return $blocks;
    case 'view':
      switch ($delta) {
        case 0:
          $block['subject'] = t('Post message');
          $block['content'] = drupal_get_form('messaging_debug_post_form');
          return $block;
        case 1:
          // Only when incoming messages are enabled
          if (module_exists('messaging_incoming')) {
            $block['subject'] = t('Incoming message');
            $block['content'] = drupal_get_form('messaging_debug_incoming_form');
            return $block;
          }
          break;
      }
      break; 
  }
}

/**
 * Incoming message form
 */
function messaging_debug_post_form() {
  global $user;

  // Availbable sending methods
  $form['method'] = array(
    '#title' => t('Send method'),
    '#type' => 'select',
    '#options' => messaging_method_list(),
    '#default_value' => messaging_method_default(),
  );
  $form['to'] = array(
    '#type' => 'textfield',
    '#title' => t('Destination'),
    '#size' => 20,
    '#autocomplete_path' => 'user/autocomplete',
    '#default_value' => $user->name, 
  );
  $form['subject'] = array(
      '#type' => 'textfield',
      '#title' => t('Subject'),
      '#size' => 20,
  );
  $form['body'] = array(
      '#type' => 'textarea',
      '#title' => t('Body'),    
  );
    
  $form['submit'] = array('#type' => 'submit', '#value' => t('Send'));
  
  return $form;
}

/**
 * Post test message
 */
function messaging_debug_post_form_submit($form, $form_state) {
  global $user;  
  
  // Convert body in array of lines
  $body = split("\n", $form_state['values']['body']);
  $body = array_map('trim', $body);
  
  $message = array(
    'type' => 'debug',
    'subject' => $form_state['values']['subject'],
    'body' => $body,  
  );
  
  // Destination may be account or plain parameter/s
  $destination = $form_state['values']['to'];
  if ($account = user_load(array('name' => $destination))) {
    $result = messaging_message_send_user($account, $message, $form_state['values']['method']);
  } else {
    $result = messaging_message_send(array($destination), $message, $form_state['values']['method']);
  }
  drupal_set_message(t('Sent message with result: %result', array('%result' => $result))); 
}


/**
 * Incoming message form
 */
function messaging_debug_incoming_form() {
  $form = array();
  // Compile a list of channels
  if ($method_list = module_invoke('messaging_incoming', 'method_info')) {
    $channels = $options = array();
    foreach ($method_list as $method => $method_info) {
      foreach (messaging_incoming_method_info($method, 'channels') as $id => $channel) {
        $key = $method . ':' . $id;
        $info[$key] = array('method' => $method, 'channel' => $id);
        $options[$key] = $method_info['name'] . ': ' . $channel['name'];
      }
    }
    $form['info'] = array('#type' => 'value', '#value' => $info);
    $form['channel'] = array(
      '#type' => 'select',
      '#title' => t('Channel'),
      '#options' => $options,
      '#default_value' => 'debug:form', // This block's channel
    );
    $form['subject'] = array(
      '#type' => 'textfield',
      '#title' => t('Subject'),
      '#size' => 15,
    );
    $form['body'] = array(
      '#type' => 'textarea',
      '#title' => t('Body'),    
    );
    $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
  }
  return $form;
}

function messaging_debug_incoming_form_submit($form, $form_state) {
  // Work out method and channel
  $info = $form_state['values']['info'][$form_state['values']['channel']];
  $message['subject'] = $form_state['values']['subject'];
  $message['body'] = $form_state['values']['body'];
  $result = messaging_message_in($info['method'], $info['channel'], $message);
  drupal_set_message(t('Processed incoming message with result: %result', array('%result' => $result ? t('OK') : t('None'))));
}

/**
 * Implementation of hook_form_alter()
 */
function messaging_debug_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'messaging_admin_settings') {
    $form['general']['messaging_debug'] = array(
      '#title' => t('Debug mode'),
      '#type' => 'radios',
      '#options' => array(t('Disabled'), t('Enabled')),
      '#default_value' => variable_get('messaging_debug', 0),
      '#description' => t('If enabled, messages wont be sent out but logged to watchdog, and displayed in the page footer.')
    );    
  }
}

/**
 * Menu callback. Display pending messages to the user
 * 
 * Sample Implementation of messaging pull methods
 */
function messaging_debug_user_page($account) {
  drupal_set_title(t('Messages for %name', array('%name' => $account->name)));
  // Fetch all pending messages.
  $output = '';
  
  // Use this method's info for all the messages
  $messages = messaging_store('get', array('uid' => $account->uid), array('mqid DESC'), MESSAGING_DEBUG_PAGER, 0);
  if ($messages) {
    $header = array(t('Method'), t('Subject'), t('Body'));
    foreach ($messages as $message) {
      // Check plain everything so we can actually see the mark up if any
      $rows[] = array($message['method'], check_plain($message['subject']), check_plain($message['body']));
    }
    $output .= theme('table', $header, $rows);
    $output .= theme('pager', array(), MESSAGING_DEBUG_PAGER); 
  } else {
    $output .=  t('No logged messages');
  }
  return $output;
}

/**
 * Implementation of hook_messaging
 */
function messaging_debug_messaging($op = 'info', $type = NULL) {
  switch($op) {
    case 'send methods':
      $info['debug'] = array(
        'title' => t('Debug'),
        'name' => t('Debug'),
        'destination' => 'name',
        'send' => 'messaging_debug_send_msg',
        'send_user' => 'messaging_debug_send_user',
        'type' => MESSAGING_TYPE_PULL,
        'glue' => '<br />',
        'description' => t('The messages will be just logged to watchdog.'),
      );
      return $info;
    case 'in methods':
      $info['debug'] = array(
        'name' => t('Debug'),
        'description' => t('Messages posted through the debug interface.'),
      );
      return $info;
    case 'in channels':
      if ($type == 'debug') {
        $info['form'] = array(
          'channel' => 'form',
          'name' => t('Debug form')
        );
        return $info;
      }
      break;
    case 'processors':
      $info['watchdog'] = array(
        'name' => t('Watchdog'),
        'process callback' => 'messaging_debug_watchdog_msg',
        'description' => t('Log message to watchdog.'),
      );
      $info['devlog'] = array(
        'name' => t('Devel log'),
        'process callback' => 'messaging_debug_devlog_msg',
        'description' => t('Log message through devel module.'),
      );
      return $info;
  }        
}

/**
 * Messaging processor
 */
function messaging_debug_watchdog_msg($message) {
  $info = $message['messaging'];
  watchdog('messaging', 'Incoming message, method %method, channel %channel: %subject', array('%method' => $info['method'], '%channel' => $info['channel'], '%subject' => $message['subject']));  
  // Return message without changes for further processing
  return $message;
}

/**
 * Message processor, just log incoming messages
 */
function messaging_debug_devlog_msg($message) {
  if (module_exists('devel')) {
    $info = $message['messaging'];
    $text = t('Incoming message, method %method, channel %channel: %subject', array('%method' => $info['%method'], '%channel' => $info['channel'], '%subject' => $message['subject']));
    dsm($message, $text);
  }
  // Return message without changes for further processing
  return $message;
}

/**
 * Just show message title to the user. 
 * 
 * This is a pull method though, so this is mainly intended for testing options
 */
function messaging_debug_send_user($account, $message, $method = 'debug') {
  $info = messaging_method_info('debug');
  $destination = array($account);
  return messaging_message_send($destination, $message, $method);
}

/**
 * Just show message title to the user. 
 * 
 * This is a pull method though, so this is mainly intended for testing options
 */
function messaging_debug_send_msg($destination, $message) {
  // Just logs everything.
  $text = '';
  $count = 0;
  $watchdog = array();
  $text  = t('Message %key for %name: %subject', array('%name' => $destination->name, '%key' => $message['type'], '%subject' => $message['subject']));
  messaging_log($text);
  // Just log message body at the end
  watchdog('messaging', 'Message %key for %name: %subject <br /> Message body: <br /><pre>!body</pre>', array('%name' => $destination->name, '%key' => $message['type'], '%subject' => $message['subject'], '!body' => $message['body']));
  return TRUE;
}

/**
 * Implementation of hook_footer()
 * 
 * Only debugging functionality for administrators, uses devel module facility
 */
function messaging_debug_footer() {
  if (user_access('administer messaging') && ($logs = messaging_log()) && function_exists('dsm')) {
    foreach ($logs as $log) {
      dsm($log);
    }
  }
}
